### ISSUE TITLE
How to force usage of python3?

### ISSUE THREAD

**Issue by Jacalz** [lv2/lilv#34]
I was recently trying to update lilv to 0.24.8 from 0.24.4 and now it installs this file:
```
/usr/lib/python2.7/site-packages/lilv.py
``` 

Is there any way to force it to use python3 or is this file even needed?

**Comment by drobilla** [comment]
It will install using whichever Python is used for the configuration/build.  e.g. `python3 ./waf configure build`

**Comment by Jacalz** [comment]
We aren't using any python3 or python2 before ./waf. The build scripts use %waf_configure that runs `./waf configure --prefix=/usr --configdir=/etc --libdir=/usr/lib64`. As our python is python2 and python3 is python3 I guess it picks up and uses python from `#!/usr/bin/env python` in that file. Will probably need to patch that unless you have a better idea :)

**Comment by mfisher31** [comment]
@Jacalz - `waf` itself is just a python script. Therefore:

`./waf ....` <- uses default python on the system
`python3 waf ...` <- forces the usage of python3.

**Comment by Jacalz** [comment]
@mfisher31 Yes I am aware of that. It is just the case that a lot of distros are using default python as python2 and python3, but python2 is dead. Might be time to start using python3 by default instead of python2.
