### ISSUE TITLE
Online documentation out of date

### ISSUE THREAD

**Issue by riban-bw** [lv2/lilv#47]
The documentation available at http://drobilla.net/docs/lilv/ seems to be for an older version of lilv than the most recently tagged v0.24.12, for example lilv_state_new_from_instance has differently named parameters and the link_dir is detailed in the correct position.

**Comment by drobilla** [comment]
Yeah, sorry, releases and `master` things are pretty stale right now as I desperately try to switch to build system and get new major versions out.  

Thanks for the head's up though, I'll try to get things up do date and moving again ASAP (but it might be a while).

**Comment by riban-bw** [comment]
Cheers! When you get to look at docs, will you check for bad html formats, e.g. in the currently published docs: https://lv2plug.in/ns/ext/presets shows:
```
Hosts SHOULD save user presets to a bundle in the user-local LV2 directory (for example ~/.lv2) with a name like &lt;Plugin_Name&gt;_&lt;Preset_Name&gt;.preset.lv2 (for example LV2_Amp_At_Eleven.preset.lv2), where names are transformed to be valid LV2 symbols for maximum compatibility.
```
i.e. html tag '&lt;' rather than '<', etc.
