### ISSUE TITLE
How do you get the LV2UI_Show_Interface?

### ISSUE THREAD

**Issue by TomCoalfish** [lv2/lilv#51]
I can't get it out of lilvmm.hpp or lilv.h I just want to call show()

**Comment by TomCoalfish** [comment]
I think I can get it to work with suil but why is there not a function to show the interface for host that don't have a GUI? It is in LV2 specification that you can get the UI Interface and call show for hosts that don't render their own frame

**Comment by TomCoalfish** [comment]
Ahhh. So, I did not even realize that not all plugins even have their GUI. Now that I understand, I can get the URI giblet to the UI. So, then maybe I can load the UI plugin.

**Comment by drobilla** [comment]
Like other "interfaces" in LV2, it is extension data, in this case on the UI.  You can retrieve it with `suil_instance_extension_data`.

https://github.com/drobilla/jalv/blob/master/src/jalv_console.c#L263
