### ISSUE TITLE
How to build the python bindings?

### ISSUE THREAD

**Issue by Eirikur** [lv2/lilv#53]
I get an empty bindings/python directory in my build directory.  Do I have to pass some option to meson build or meson compile?

**Comment by drobilla** [comment]
> I get an empty bindings/python directory in my build directory.

As expected, there is nothing to "build".  The bindings will be installed.

> Do I have to pass some option to meson build or meson compile?

No, it is automatically built/installed if possible, like most things, but you can set bindings_py=enabled to force it on.
