### ISSUE TITLE
Bad decoding of \\ characters

### ISSUE THREAD

**Issue by falkTX** [lv2/lilv#61]
reporting a ticket that is likely on serd or sord side, but I am having trouble finding exactly what is wrong.

take a plugin that writes json in a string parameter, saving state like so:
```
{
  "id": 1079059256177472,
  "plugin": "Cardinal",
  "model": "TextEditor",
  "version": "2.0",
  "params": [],
  "data": {
    "filepath": "",
    "lang": "None",
    "etext": "\n\n1 - LP Filter\n2 - Resonance\n3 - OSC 1 <> 2\n4 - Attack\n5 - Decay\n6 - Sustain\n\n\n\n\n\n",
    "width": 11
  },
  "pos": [
    48,
    0
  ]
}
```

this is valid json, verified by json linters, all fine so far.

when saving this as plugin state with lilv, the state/preset ttl contents end up alike this:

```
{
  "id": 7797650034473482,
  "plugin": "Cardinal",
  "model": "TextEditor",
  "version": "2.0",
  "params": [],
  "leftModuleId": 7219430607288126,
  "data": {
    "filepath": "",
    "lang": "None",
    "etext": "\\n\\nThis section spreads\\n\\nthe unison sound\\n\\nacross 4 stereo outs\\n\\n\\n\\n\\n\\n\\n",
    "width": 14
  },
  "pos": [
    31,
    1
  ]
}
```

There is some extra encoding of the \ characters, but seems consistent in what it does.

When loading this state, this is the string given to the plugin as state which sadly becomes invalid:

```
{
  "id": 7797650034473482,
  "plugin": "Cardinal",
  "model": "TextEditor",
  "version": "2.0",
  "params": [],
  "leftModuleId": 7219430607288126,
  "data": {
    "filepath": "",
    "lang": "None",
    "etext": "\
\nThis section spreads\n\nthe unison sound\n\nacross 4 stereo outs\n\n\n\n\n\n\n",
    "width": 14
  },
  "pos": [
    31,
    1
  ]
}
```

compare the 1st to 3rd code-blocks on this ticket, the "etext" has a real newline in there which is invalid in JSON. only happens on the 1st occurrence weirdly enough.

initially I thought this was a bug on my side, but I dumped the state from lilv directly into a file, and that file content is what you see on this 3rd pasted code block.
seems like something on lilv or libs used by it is not decoding back the values properly.

issue has been there for a while, and also present on very recent lilv/lv2 libs too.
only reporting it now since I assumed I did something wrong, but now I am not so certain anymore...

**Comment by falkTX** [comment]
note here: the string posted in the code blocks were always read from files, so a `\n` is as shown on a text editor, and not specially escaped character.

**Comment by drobilla** [comment]
Hm... that's weird.  The double escaping seems roughly as expected (`\n` is two JSON characters, the `\` needs to be escaped, so you get `\\n`), but I don't know why the first character would be botched.  Maybe there's some whitespace trimming somewhere that's getting confused...

What's the least fiddly way to reproduce?

**Comment by falkTX** [comment]
any plugin that can save a string and state, is there some example plugin that allows arbitrary input? that should do it..

**Comment by falkTX** [comment]
can reproduce with jalv and an example plugin.

```
jalv.gtk http://lv2plug.in/plugins/eg-params
```

easy steps:
1. run jalv
2. copy and paste the 1st code block from the ticket into the "hello world" string entry
3. click away so the message is received by the plugin
4. save preset
5. close and reopen jalv
6. try to open the saved preset
7. copy&paste the string and notice how the json got botched up

**Comment by drobilla** [comment]
Just tried that with the current git versions of everything and it seems to work fine.

Which versions of lilv/serd/sord/jalv are you using?

**Comment by falkTX** [comment]
jalv 1.6.6
lilv 0.24.14
sratom 0.6.10
sord 0.16.10
serd 0.30.12

I see these are a bit old by now, were there changes recently related to this?

**Comment by falkTX** [comment]
I also had the issue in a different host, using these versions:

lilv 0.24.20
sratom 0.6.14
sord 0.16.14
serd 0.30.16

which are a bit more up to date, but still not latest.

**Comment by drobilla** [comment]
There _are_ some changes to Turtle/TriG stuff in serd 0.32.0, although mostly superficial pretty-printing improvements.  There is  002e2edc7fee5297b1bc8e1da4932d38e270f8f8, however...

**Comment by falkTX** [comment]
Can confirm the issue was that commit, by backporting it to my current release (it is a bit tricky to update as build systems changed in between releases, and cross-compiling with meson can be a pain)

Thanks for pointing to that commit in specific, glad to see this working now.

**Comment by drobilla** [comment]
Ah, I see.  This was my confusion since I knew you were already on the meson train.
