### ISSUE TITLE
lv2apply uses non-portable Variable Length Arrays (VLA)

### ISSUE THREAD

**Issue by dg0yt** [lv2/lilv#64]
https://github.com/lv2/lilv/blob/b6496d8b5d109d8fd1268a917eb70a447868bef3/tools/lv2apply.c#L324-L325

These lines fail to compile with MSVC.

This was noticed while reviewing a regression of the vcpkg port. The issue occurs only for a particular configuration. 
- Feature `tools` left to default. (Not forced to enabled or disabled.)
- Dependency `sndfile` can be found.

**Comment by drobilla** [comment]
Fixed in e1e0b34

**Comment by dg0yt** [comment]
Thanks.
